export type Industry =
  | 'technology'
  | 'business_management'
  | 'creative_design'
  | 'healthcare'
  | 'education'
  | 'finance_legal'
  | 'science_research'
  | 'arts_entertainment'
  | 'hospitality_tourism'
  | 'sports_fitness'
  | 'manufacturing_engineering'
  | 'agriculture_environment'
  | 'media_communication'
  | 'transportation_logistics'
  | 'construction_trades'
  | 'government_public_service'
  | 'nonprofit_social_impact'
  | 'other';

export const INDUSTRY_LABELS: Record<Industry, string> = {
  technology: 'Technology & Software',
  business_management: 'Business & Management',
  creative_design: 'Creative & Design',
  healthcare: 'Healthcare & Medical',
  education: 'Education & Training',
  finance_legal: 'Finance & Legal',
  science_research: 'Science & Research',
  arts_entertainment: 'Arts & Entertainment',
  hospitality_tourism: 'Hospitality & Tourism',
  sports_fitness: 'Sports & Fitness',
  manufacturing_engineering: 'Manufacturing & Engineering',
  agriculture_environment: 'Agriculture & Environment',
  media_communication: 'Media & Communication',
  transportation_logistics: 'Transportation & Logistics',
  construction_trades: 'Construction & Trades',
  government_public_service: 'Government & Public Service',
  nonprofit_social_impact: 'Nonprofit & Social Impact',
  other: 'Other'
};

// Map job titles to their respective industries
export const INDUSTRY_JOB_TITLES: Record<Industry, string[]> = {
  technology: [
    'Software Engineer',
    'Full Stack Developer',
    'Frontend Developer',
    'Backend Developer',
    'Mobile Developer',
    'iOS Developer',
    'Android Developer',
    'React Developer',
    'Angular Developer',
    'Vue.js Developer',
    'Node.js Developer',
    'Python Developer',
    'Java Developer',
    'C# Developer',
    'Ruby Developer',
    'PHP Developer',
    'Golang Developer',
    'Rust Developer',
    'Blockchain Developer',
    'Smart Contract Developer',
    'DevOps Engineer',
    'Site Reliability Engineer',
    'Cloud Architect',
    'AWS Solutions Architect',
    'Azure Cloud Engineer',
    'Google Cloud Engineer',
    'Data Scientist',
    'Data Engineer',
    'Data Analyst',
    'Business Intelligence Analyst',
    'Machine Learning Engineer',
    'AI Researcher',
    'Deep Learning Specialist',
    'NLP Engineer',
    'Computer Vision Engineer',
    'Product Manager',
    'Technical Product Manager',
    'Product Owner',
    'UX Designer',
    'UI Designer',
    'UX Researcher',
    'Interaction Designer',
    'Visual Designer',
    'QA Engineer',
    'Test Automation Engineer',
    'Security Engineer',
    'Cybersecurity Analyst',
    'Penetration Tester',
    'Information Security Officer',
    'Systems Administrator',
    'Database Administrator',
    'Network Engineer',
    'Network Administrator',
    'Technical Lead',
    'Engineering Manager',
    'CTO',
    'CIO',
    'CISO',
    'IT Manager',
    'IT Support Specialist',
    'Scrum Master',
    'Agile Coach',
    'Technical Writer',
    'Game Developer',
    'Unity Developer',
    'Unreal Engine Developer',
    'AR/VR Developer',
    'Embedded Systems Engineer',
    'IoT Developer',
    'Robotics Engineer',
    'Quantum Computing Researcher'
  ],
  business_management: [
    'CEO',
    'COO',
    'CFO',
    'Chief Marketing Officer',
    'Chief Revenue Officer',
    'Chief People Officer',
    'Chief Strategy Officer',
    'Chief Growth Officer',
    'Business Analyst',
    'Business Systems Analyst',
    'Project Manager',
    'Program Manager',
    'Product Operations Manager',
    'Operations Manager',
    'Operations Director',
    'Account Manager',
    'Key Account Manager',
    'Sales Manager',
    'Sales Director',
    'Sales Representative',
    'Business Development Representative',
    'Business Development Manager',
    'Marketing Manager',
    'Digital Marketing Manager',
    'Content Marketing Manager',
    'Growth Marketing Manager',
    'Brand Manager',
    'SEO Specialist',
    'SEM Specialist',
    'PPC Specialist',
    'Email Marketing Specialist',
    'Social Media Manager',
    'Community Manager',
    'PR Manager',
    'Public Relations Specialist',
    'HR Manager',
    'HR Business Partner',
    'Talent Acquisition Specialist',
    'Recruiter',
    'Technical Recruiter',
    'People Operations Manager',
    'Learning & Development Manager',
    'Compensation & Benefits Manager',
    'Strategy Consultant',
    'Management Consultant',
    'Financial Analyst',
    'Investment Banker',
    'Venture Capitalist',
    'Private Equity Associate',
    'Mergers & Acquisitions Specialist',
    'Business Intelligence Manager',
    'Office Manager',
    'Executive Assistant',
    'Administrative Assistant',
    'Customer Success Manager',
    'Customer Experience Manager',
    'Client Relationship Manager'
  ],
  creative_design: [
    'Graphic Designer',
    'Senior Graphic Designer',
    'Art Director',
    'Creative Director',
    'Visual Designer',
    'Brand Designer',
    'Motion Designer',
    '3D Designer',
    'Illustrator',
    'Animator',
    'Character Designer',
    'Storyboard Artist',
    'Photographer',
    'Videographer',
    'Video Editor',
    'Film Editor',
    'Sound Designer',
    'Audio Engineer',
    'Content Creator',
    'Content Strategist',
    'Copywriter',
    'Technical Copywriter',
    'UX Writer',
    'Content Editor',
    'Editor-in-Chief',
    'Managing Editor',
    'Journalist',
    'Reporter',
    'Social Media Content Creator',
    'Digital Marketing Specialist',
    'SEO Content Writer',
    'Interior Designer',
    'Fashion Designer',
    'Textile Designer',
    'Industrial Designer',
    'Product Designer',
    'Packaging Designer',
    'Web Designer',
    'Email Designer',
    'Print Designer',
    'Exhibition Designer',
    'Game Artist',
    'Concept Artist',
    'Environment Artist',
    'Character Artist',
    'UI Artist',
    'Animation Artist',
    'VFX Artist',
    'Architectural Visualizer'
  ],
  healthcare: [
    'Doctor',
    'Physician',
    'General Practitioner',
    'Specialist Physician',
    'Surgeon',
    'Cardiologist',
    'Neurologist',
    'Pediatrician',
    'Psychiatrist',
    'Dermatologist',
    'Ophthalmologist',
    'Anesthesiologist',
    'Radiologist',
    'Oncologist',
    'Nurse',
    'Registered Nurse',
    'Nurse Practitioner',
    'Clinical Nurse Specialist',
    'Nurse Anesthetist',
    'Nurse Midwife',
    'Dentist',
    'Orthodontist',
    'Dental Hygienist',
    'Pharmacist',
    'Clinical Pharmacist',
    'Pharmacy Technician',
    'Physical Therapist',
    'Occupational Therapist',
    'Speech Therapist',
    'Respiratory Therapist',
    'Psychologist',
    'Clinical Psychologist',
    'Neuropsychologist',
    'Veterinarian',
    'Veterinary Technician',
    'Medical Researcher',
    'Clinical Research Coordinator',
    'Biomedical Scientist',
    'Epidemiologist',
    'Healthcare Administrator',
    'Hospital Administrator',
    'Medical Director',
    'Healthcare Consultant',
    'Nutritionist',
    'Dietitian',
    'Paramedic',
    'Emergency Medical Technician',
    'Medical Assistant',
    'Physician Assistant',
    'Medical Laboratory Technician',
    'Radiologic Technologist',
    'Ultrasound Technician',
    'MRI Technologist',
    'Phlebotomist',
    'Medical Coder',
    'Medical Biller',
    'Health Information Technician',
    'Public Health Specialist',
    'Healthcare Data Analyst'
  ],
  education: [
    'Teacher',
    'Elementary School Teacher',
    'Middle School Teacher',
    'High School Teacher',
    'Special Education Teacher',
    'ESL Teacher',
    'STEM Teacher',
    'Music Teacher',
    'Art Teacher',
    'Physical Education Teacher',
    'Professor',
    'Associate Professor',
    'Assistant Professor',
    'Adjunct Professor',
    'Lecturer',
    'Principal',
    'Vice Principal',
    'School Administrator',
    'Dean',
    'Department Chair',
    'Academic Advisor',
    'College Counselor',
    'Education Consultant',
    'Curriculum Developer',
    'Instructional Designer',
    'E-learning Developer',
    'Educational Technologist',
    'School Counselor',
    'School Psychologist',
    'Educational Psychologist',
    'Research Associate',
    'Research Assistant',
    'Teaching Assistant',
    'Graduate Assistant',
    'Librarian',
    'School Librarian',
    'Research Librarian',
    'Education Coordinator',
    'Program Coordinator',
    'Career Counselor',
    'Admissions Officer',
    'Registrar',
    'Financial Aid Counselor',
    'Student Affairs Coordinator',
    'Student Success Coach',
    'Tutor',
    'Early Childhood Educator',
    'Preschool Teacher',
    'Childcare Worker',
    'Education Policy Analyst',
    'Education Researcher'
  ],
  finance_legal: [
    'Lawyer',
    'Attorney',
    'Corporate Lawyer',
    'Litigation Attorney',
    'Patent Attorney',
    'Tax Attorney',
    'Immigration Lawyer',
    'Family Lawyer',
    'Criminal Defense Lawyer',
    'Legal Consultant',
    'Legal Counsel',
    'General Counsel',
    'Judge',
    'Paralegal',
    'Legal Assistant',
    'Law Clerk',
    'Accountant',
    'Certified Public Accountant',
    'Chartered Accountant',
    'Forensic Accountant',
    'Tax Accountant',
    'Tax Advisor',
    'Tax Consultant',
    'Financial Planner',
    'Certified Financial Planner',
    'Financial Advisor',
    'Wealth Manager',
    'Investment Advisor',
    'Portfolio Manager',
    'Fund Manager',
    'Hedge Fund Manager',
    'Private Equity Manager',
    'Risk Manager',
    'Risk Analyst',
    'Compliance Officer',
    'Regulatory Compliance Specialist',
    'Insurance Agent',
    'Insurance Broker',
    'Insurance Underwriter',
    'Claims Adjuster',
    'Real Estate Agent',
    'Real Estate Broker',
    'Real Estate Appraiser',
    'Mortgage Broker',
    'Loan Officer',
    'Credit Analyst',
    'Auditor',
    'Internal Auditor',
    'External Auditor',
    'Treasurer',
    'Financial Controller',
    'Actuary',
    'Economist',
    'Financial Analyst',
    'Investment Analyst',
    'Equity Analyst',
    'Quantitative Analyst',
    'Legal Secretary',
    'Bankruptcy Specialist',
    'Estate Planning Attorney'
  ],
  science_research: [
    'Research Scientist',
    'Principal Investigator',
    'Research Associate',
    'Research Assistant',
    'Laboratory Manager',
    'Laboratory Technician',
    'Biologist',
    'Molecular Biologist',
    'Cell Biologist',
    'Marine Biologist',
    'Microbiologist',
    'Biochemist',
    'Geneticist',
    'Chemist',
    'Analytical Chemist',
    'Organic Chemist',
    'Inorganic Chemist',
    'Medicinal Chemist',
    'Physicist',
    'Theoretical Physicist',
    'Experimental Physicist',
    'Astrophysicist',
    'Astronomer',
    'Environmental Scientist',
    'Ecologist',
    'Conservation Scientist',
    'Geologist',
    'Geophysicist',
    'Meteorologist',
    'Climatologist',
    'Oceanographer',
    'Clinical Research Coordinator',
    'Clinical Trial Manager',
    'Biomedical Engineer',
    'Biomedical Scientist',
    'Forensic Scientist',
    'Forensic Analyst',
    'Food Scientist',
    'Nutritional Scientist',
    'Materials Scientist',
    'Nanotechnology Researcher',
    'Research Director',
    'Science Director',
    'Patent Examiner',
    'Science Writer',
    'Technical Writer',
    'Science Communicator',
    'Laboratory Supervisor',
    'Data Analyst',
    'Statistical Analyst',
    'Biostatistician',
    'Neuroscientist',
    'Cognitive Scientist',
    'Immunologist',
    'Virologist',
    'Toxicologist',
    'Pharmacologist'
  ],
  arts_entertainment: [
    'Actor',
    'Actress',
    'Voice Actor',
    'Theater Actor',
    'Film Actor',
    'Musician',
    'Singer',
    'Songwriter',
    'Composer',
    'Music Producer',
    'DJ',
    'Dancer',
    'Choreographer',
    'Producer',
    'Film Producer',
    'TV Producer',
    'Executive Producer',
    'Director',
    'Film Director',
    'Creative Director',
    'Art Director',
    'Technical Director',
    'Film Editor',
    'Video Editor',
    'Sound Engineer',
    'Audio Engineer',
    'Lighting Designer',
    'Lighting Technician',
    'Stage Manager',
    'Production Manager',
    'Production Assistant',
    'Talent Agent',
    'Talent Manager',
    'Casting Director',
    'Music Teacher',
    'Vocal Coach',
    'Art Curator',
    'Gallery Owner',
    'Art Dealer',
    'Theater Manager',
    'Venue Manager',
    'Costume Designer',
    'Wardrobe Stylist',
    'Set Designer',
    'Prop Master',
    'Makeup Artist',
    'Special Effects Makeup Artist',
    'Performance Artist',
    'Circus Performer',
    'Magician',
    'Comedian',
    'Screenwriter',
    'Playwright',
    'Novelist',
    'Author',
    'Poet',
    'Script Supervisor',
    'Stunt Performer',
    'Stunt Coordinator'
  ],
  hospitality_tourism: [
    'Chef',
    'Executive Chef',
    'Sous Chef',
    'Pastry Chef',
    'Line Cook',
    'Baker',
    'Restaurant Manager',
    'Food and Beverage Manager',
    'Restaurant Owner',
    'Restaurateur',
    'Sommelier',
    'Bartender',
    'Mixologist',
    'Barista',
    'Server',
    'Waiter/Waitress',
    'Host/Hostess',
    'Hotel Manager',
    'Hotel General Manager',
    'Front Desk Manager',
    'Front Desk Agent',
    'Concierge',
    'Housekeeping Manager',
    'Housekeeper',
    'Event Planner',
    'Event Coordinator',
    'Wedding Planner',
    'Conference Coordinator',
    'Travel Agent',
    'Travel Consultant',
    'Tour Guide',
    'Tour Operator',
    'Tour Director',
    'Flight Attendant',
    'Pilot',
    'Cruise Director',
    'Cruise Ship Staff',
    'Resort Manager',
    'Resort Activities Director',
    'Casino Manager',
    'Casino Dealer',
    'Tourism Coordinator',
    'Tourism Development Officer',
    'Guest Relations Manager',
    'Guest Experience Manager',
    'Catering Manager',
    'Catering Coordinator',
    'Food Service Director',
    'Spa Manager',
    'Spa Therapist',
    'Massage Therapist',
    'Recreation Director',
    'Theme Park Manager',
    'Attraction Manager'
  ],
  sports_fitness: [
    'Personal Trainer',
    'Fitness Instructor',
    'Group Fitness Instructor',
    'Yoga Instructor',
    'Pilates Instructor',
    'CrossFit Coach',
    'Strength and Conditioning Coach',
    'Athletic Coach',
    'Sports Coach',
    'Head Coach',
    'Assistant Coach',
    'Sports Manager',
    'Team Manager',
    'Athletic Director',
    'Sports Administrator',
    'Sports Agent',
    'Sports Therapist',
    'Physical Therapist',
    'Sports Psychologist',
    'Sports Nutritionist',
    'Dietitian',
    'Sports Medicine Physician',
    'Athletic Trainer',
    'Professional Athlete',
    'Sports Analyst',
    'Sports Commentator',
    'Sports Journalist',
    'Sports Photographer',
    'Sports Marketing Manager',
    'Sports Event Coordinator',
    'Gym Manager',
    'Fitness Center Director',
    'Recreation Coordinator',
    'Outdoor Activities Guide',
    'Adventure Guide',
    'Ski Instructor',
    'Snowboard Instructor',
    'Swimming Instructor',
    'Lifeguard',
    'Diving Instructor',
    'Golf Instructor',
    'Tennis Coach',
    'Referee',
    'Umpire',
    'Sports Official',
    'Physical Education Teacher',
    'Dance Instructor',
    'Martial Arts Instructor',
    'Boxing Coach',
    'Gymnastics Coach',
    'Sports Facility Manager',
    'Stadium Operations Manager'
  ],
  manufacturing_engineering: [
    'Mechanical Engineer',
    'Electrical Engineer',
    'Civil Engineer',
    'Structural Engineer',
    'Chemical Engineer',
    'Industrial Engineer',
    'Manufacturing Engineer',
    'Process Engineer',
    'Quality Engineer',
    'Aerospace Engineer',
    'Automotive Engineer',
    'Petroleum Engineer',
    'Nuclear Engineer',
    'Biomedical Engineer',
    'Environmental Engineer',
    'Materials Engineer',
    'Mining Engineer',
    'Marine Engineer',
    'Engineering Manager',
    'Engineering Director',
    'Plant Manager',
    'Production Manager',
    'Operations Manager',
    'Quality Control Manager',
    'Quality Assurance Manager',
    'Supply Chain Manager',
    'Logistics Manager',
    'Procurement Manager',
    'Purchasing Manager',
    'Inventory Manager',
    'Warehouse Manager',
    'Production Supervisor',
    'Shift Supervisor',
    'Maintenance Manager',
    'Maintenance Technician',
    'CNC Machinist',
    'Tool and Die Maker',
    'Welder',
    'Fabricator',
    'Assembly Line Worker',
    'Production Worker',
    'Machine Operator',
    'Forklift Operator',
    'Safety Manager',
    'Environmental Health and Safety Specialist',
    'Compliance Manager',
    'Facilities Manager',
    'Facilities Technician',
    'CAD Designer',
    'Drafter',
    'Technical Illustrator'
  ],
  agriculture_environment: [
    'Farmer',
    'Agricultural Manager',
    'Farm Manager',
    'Agricultural Scientist',
    'Agronomist',
    'Soil Scientist',
    'Crop Scientist',
    'Horticulturist',
    'Viticulturist',
    'Livestock Manager',
    'Veterinarian',
    'Veterinary Technician',
    'Agricultural Engineer',
    'Agricultural Consultant',
    'Agricultural Economist',
    'Food Safety Inspector',
    'Environmental Scientist',
    'Environmental Consultant',
    'Environmental Engineer',
    'Conservation Scientist',
    'Wildlife Biologist',
    'Marine Biologist',
    'Ecologist',
    'Forester',
    'Park Ranger',
    'Landscape Architect',
    'Landscape Designer',
    'Arborist',
    'Botanist',
    'Greenhouse Manager',
    'Nursery Manager',
    'Fishery Manager',
    'Aquaculture Technician',
    'Sustainability Consultant',
    'Renewable Energy Specialist',
    'Solar Energy Technician',
    'Wind Energy Technician',
    'Waste Management Specialist',
    'Recycling Coordinator',
    'Water Resource Specialist',
    'Hydrologist',
    'Climate Change Analyst',
    'Environmental Policy Analyst',
    'Environmental Educator',
    'Conservation Officer',
    'Natural Resource Manager',
    'Organic Farming Specialist',
    'Permaculture Designer',
    'Urban Farmer',
    'Apiarist/Beekeeper'
  ],
  media_communication: [
    'Journalist',
    'Reporter',
    'News Anchor',
    'Broadcast Journalist',
    'Investigative Journalist',
    'Photojournalist',
    'Editor',
    'Copy Editor',
    'Managing Editor',
    'Content Editor',
    'Publisher',
    'Publishing Director',
    'Literary Agent',
    'Book Editor',
    'Proofreader',
    'Copywriter',
    'Content Writer',
    'Technical Writer',
    'Ghostwriter',
    'Blogger',
    'Social Media Manager',
    'Social Media Specialist',
    'Digital Content Producer',
    'Content Strategist',
    'SEO Specialist',
    'Public Relations Manager',
    'PR Specialist',
    'Media Relations Manager',
    'Communications Director',
    'Corporate Communications Manager',
    'Internal Communications Specialist',
    'Crisis Communications Manager',
    'Spokesperson',
    'Press Secretary',
    'Speech Writer',
    'Translator',
    'Interpreter',
    'Localization Specialist',
    'Radio Producer',
    'Radio Host',
    'Podcast Producer',
    'Podcaster',
    'TV Producer',
    'TV Host',
    'Broadcast Technician',
    'Camera Operator',
    'Videographer',
    'Film Producer',
    'Documentary Filmmaker',
    'Media Planner',
    'Advertising Executive',
    'Brand Strategist'
  ],
  transportation_logistics: [
    'Pilot',
    'Commercial Pilot',
    'Airline Pilot',
    'Flight Instructor',
    'Air Traffic Controller',
    'Flight Dispatcher',
    'Aircraft Mechanic',
    'Aviation Technician',
    'Truck Driver',
    'Delivery Driver',
    'Courier',
    'Bus Driver',
    'Taxi Driver',
    'Chauffeur',
    'Train Operator',
    'Locomotive Engineer',
    'Conductor',
    'Ship Captain',
    'Merchant Marine',
    'Sailor',
    'Deckhand',
    'Marine Engineer',
    'Port Manager',
    'Harbor Master',
    'Logistics Manager',
    'Logistics Coordinator',
    'Supply Chain Manager',
    'Supply Chain Analyst',
    'Inventory Manager',
    'Warehouse Manager',
    'Warehouse Supervisor',
    'Distribution Manager',
    'Transportation Manager',
    'Fleet Manager',
    'Freight Forwarder',
    'Customs Broker',
    'Import/Export Specialist',
    'Shipping Coordinator',
    'Logistics Analyst',
    'Route Planner',
    'Traffic Manager',
    'Dispatcher',
    'Transportation Planner',
    'Urban Mobility Specialist',
    'Automotive Technician',
    'Diesel Mechanic',
    'Aviation Manager',
    'Railway Operations Manager',
    'Maritime Operations Manager',
    'Drone Operator',
    'Autonomous Vehicle Specialist'
  ],
  construction_trades: [
    'Construction Manager',
    'Project Manager',
    'General Contractor',
    'Construction Superintendent',
    'Site Manager',
    'Civil Engineer',
    'Structural Engineer',
    'Architect',
    'Architectural Designer',
    'Drafter',
    'CAD Technician',
    'Building Inspector',
    'Safety Inspector',
    'Surveyor',
    'Land Surveyor',
    'Quantity Surveyor',
    'Estimator',
    'Cost Estimator',
    'Carpenter',
    'Master Carpenter',
    'Framer',
    'Electrician',
    'Master Electrician',
    'Plumber',
    'Master Plumber',
    'HVAC Technician',
    'HVAC Engineer',
    'Welder',
    'Pipefitter',
    'Steamfitter',
    'Mason',
    'Bricklayer',
    'Stonemason',
    'Roofer',
    'Painter',
    'Drywall Installer',
    'Plasterer',
    'Flooring Installer',
    'Tile Setter',
    'Glazier',
    'Insulation Installer',
    'Landscaper',
    'Landscape Designer',
    'Groundskeeper',
    'Equipment Operator',
    'Crane Operator',
    'Bulldozer Operator',
    'Excavator Operator',
    'Demolition Specialist',
    'Elevator Installer',
    'Solar Panel Installer',
    'Wind Turbine Technician'
  ],
  government_public_service: [
    'Government Official',
    'Elected Official',
    'Mayor',
    'Governor',
    'Senator',
    'Representative',
    'Diplomat',
    'Foreign Service Officer',
    'Policy Advisor',
    'Policy Analyst',
    'Legislative Aide',
    'Political Consultant',
    'Campaign Manager',
    'Public Administrator',
    'City Manager',
    'Urban Planner',
    'City Planner',
    'Civil Servant',
    'Government Analyst',
    'Intelligence Analyst',
    'Intelligence Officer',
    'Military Officer',
    'Military Personnel',
    'Veteran',
    'Police Officer',
    'Detective',
    'Sheriff',
    'State Trooper',
    'Federal Agent',
    'FBI Agent',
    'DEA Agent',
    'Border Patrol Agent',
    'Customs Officer',
    'Immigration Officer',
    'Firefighter',
    'Fire Chief',
    'Paramedic',
    'EMT',
    'Emergency Manager',
    'Disaster Response Coordinator',
    'Public Health Official',
    'Public Health Inspector',
    'Environmental Health Officer',
    'Postal Worker',
    'Mail Carrier',
    'Postal Service Clerk',
    'Tax Examiner',
    'IRS Agent',
    'Social Worker',
    'Child Welfare Specialist',
    'Probation Officer',
    'Parole Officer',
    'Correctional Officer'
  ],
  nonprofit_social_impact: [
    'Nonprofit Executive Director',
    'Nonprofit Manager',
    'Program Director',
    'Program Manager',
    'Program Coordinator',
    'Grant Writer',
    'Grant Manager',
    'Fundraiser',
    'Development Director',
    'Donor Relations Manager',
    'Volunteer Coordinator',
    'Community Organizer',
    'Community Outreach Coordinator',
    'Social Worker',
    'Case Manager',
    'Mental Health Counselor',
    'Family Counselor',
    'Youth Counselor',
    'Substance Abuse Counselor',
    'Victim Advocate',
    'Human Rights Advocate',
    'Environmental Advocate',
    'Animal Welfare Specialist',
    'Wildlife Conservationist',
    'Humanitarian Aid Worker',
    'International Development Specialist',
    'Peace Corps Volunteer',
    'Disaster Relief Coordinator',
    'Crisis Response Manager',
    'Refugee Coordinator',
    'Immigration Counselor',
    'ESL Teacher',
    'Literacy Specialist',
    'Special Needs Advocate',
    'Disability Services Coordinator',
    'Elder Care Specialist',
    'Hospice Worker',
    'Public Health Educator',
    'Community Health Worker',
    'Food Bank Manager',
    'Homeless Shelter Coordinator',
    'Affordable Housing Specialist',
    'Social Justice Advocate',
    'Policy Advocate',
    'Lobbyist',
    'Campaign Organizer',
    'Civic Engagement Coordinator',
    'Volunteer'
  ],
  other: [
    'Freelancer',
    'Independent Contractor',
    'Entrepreneur',
    'Small Business Owner',
    'Startup Founder',
    'Co-founder',
    'Solopreneur',
    'Consultant',
    'Advisor',
    'Coach',
    'Life Coach',
    'Career Coach',
    'Executive Coach',
    'Business Coach',
    'Mentor',
    'Speaker',
    'Public Speaker',
    'Keynote Speaker',
    'Author',
    'Writer',
    'Blogger',
    'Influencer',
    'Content Creator',
    'Podcaster',
    'YouTuber',
    'Streamer',
    'Researcher',
    'Academic',
    'Scholar',
    'Student',
    'Graduate Student',
    'PhD Candidate',
    'Postdoctoral Researcher',
    'Fellow',
    'Intern',
    'Apprentice',
    'Trainee',
    'Volunteer',
    'Board Member',
    'Trustee',
    'Advisor',
    'Investor',
    'Angel Investor',
    'Retired',
    'Homemaker',
    'Caregiver',
    'Self-Employed',
    'Digital Nomad',
    'Remote Worker',
    'Gig Worker',
    'Other'
  ]
};