// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxnlnagnmncffjekkvkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14bmxuYWdubW5jZmZqZWtrdmtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTg1MTAsImV4cCI6MjA2OTczNDUxMH0.NhUF8yjJMT2FofEk9sw16t7a1PCw50dSDcnZLbZIj7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});